### ISSUE TITLE
Inquiry about Update Status for React Storefront Connector Compatibility

### ISSUE THREAD

**Issue by abdessamad-adane** [storefront-foundation/react-storefront-v6-shopify#5]
Greetings,

I hope this message finds you well. _I'm reaching out regarding the React Storefront connector for Shopify_, as I've encountered compatibility issues with the current version of React Storefront.

The existing connector seems to be incompatible with the latest iteration of React Storefront. I wanted to inquire about the possibility of an update or any plans in the pipeline to ensure compatibility with the latest versions.

As our team is eager to utilize React Storefront for our Shopify integration, an updated connector or guidance on handling the integration directly would be immensely helpful. We are committed to contributing to or collaborating on this effort if needed.

Could you kindly provide insights into the update status of the connector or suggest alternative approaches or resources that might assist in achieving seamless integration with the current React Storefront version?

Thank you very much for your time and assistance. We're looking forward to your guidance and support in resolving this matter.

Best regards,
Abdessamad

**Comment by ianand** [comment]
We’re working on a new version but it's not ready yet. Please DM me referencing this issue on Twitter or Linkedin and we can chat further.
